# Generated by Django 3.2.6 on 2021-08-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='After_Implementation_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Before_Implementation_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='During_Implementation_Case_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='During_Implementation_Monthly_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estimated_Amount_Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_coefficient', models.FloatField()),
                ('steel_coefficient', models.FloatField()),
                ('rural_water_coefficient', models.FloatField()),
                ('shipping_coefficient', models.FloatField()),
                ('under_pressure_irrigation_coefficient', models.FloatField()),
                ('mechanical_facilities_coefficient', models.FloatField()),
                ('electrical_facilities_coefficient', models.FloatField()),
                ('railway_airport_highways_coefficient', models.FloatField()),
                ('railway_airport_highways_type_1_2_coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_name', models.CharField(max_length=160)),
                ('base_price', models.IntegerField(blank=True, null=True)),
                ('time_duration', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='During_Implementation_Monthly_Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
                ('deliverable', models.CharField(max_length=100)),
                ('base_price', models.IntegerField(blank=True, null=True)),
                ('during_implementation_monthly_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.during_implementation_monthly_title')),
            ],
        ),
        migrations.CreateModel(
            name='During_Implementation_Case_Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
                ('deliverable', models.CharField(max_length=100)),
                ('base_price', models.IntegerField(blank=True, null=True)),
                ('repetition', models.IntegerField(blank=True, null=True)),
                ('during_implementation_case_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.during_implementation_case_title')),
            ],
        ),
        migrations.CreateModel(
            name='Before_Implementation_Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
                ('deliverable', models.CharField(max_length=100)),
                ('base_price', models.IntegerField(blank=True, null=True)),
                ('before_implementation_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.before_implementation_title')),
            ],
        ),
        migrations.CreateModel(
            name='After_Implementation_Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('row_description', models.CharField(max_length=150)),
                ('deliverable', models.CharField(max_length=100)),
                ('base_price', models.IntegerField(blank=True, null=True)),
                ('after_implementation_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.after_implementation_title')),
            ],
        ),
    ]
